services:
  db:
    image: postgres:17.5-alpine
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/take-home-edify-sde-full-stack-mid-level
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "bun run db:push && bun run start"
    volumes:
      - .:/app
      - /app/node_modules # Exclude node_modules from host mount to prevent issues

volumes:
  db_data:
